## Simple Imputation

### 1) Mean Imputation

In [ ]:
# Simple Impute
from sklearn.impute import SimpleImputer
import numpy as np

# Numeric example
# Create Dataset
data = [ [2, 4, np.nan],
         [8, np.nan, 12],
         [np.nan, 16 ,18]]

# Imputation object
# use means imputation
imputer = SimpleImputer(strategy="mean")
data_imputed = imputer.fit_transform(data)

print(data_imputed)

[[ 2.  4. 15.]
 [ 8. 10. 12.]
 [ 5. 16. 18.]]


### 2) Median Imputation

In [3]:
# Imputation object
# use means imputation
imputer = SimpleImputer(strategy="median")
data_imputed = imputer.fit_transform(data)

print(data_imputed)

[[ 2.  4. 15.]
 [ 8. 10. 12.]
 [ 5. 16. 18.]]


### 3) Most Frequent Imputation (Mode Imputation)

In [4]:
# Imputation object
# use means imputation
imputer = SimpleImputer(strategy="most_frequent")
data_imputed = imputer.fit_transform(data)

print(data_imputed)

[[ 2.  4. 12.]
 [ 8.  4. 12.]
 [ 2. 16. 18.]]


## KNN Imputation 

In [2]:
# KNNImpute
from sklearn.impute import KNNImputer
import numpy as np


# create dataset
data = [ [2, 4, np.nan],
         [8, np.nan, 12],
         [np.nan, 16 ,18]]

# Imputation object assign NNeighrest Neighbour 
imputer = KNNImputer(n_neighbors=2)
data_imputed = imputer.fit_transform(data)

print(data_imputed)

[[ 2.  4. 15.]
 [ 8. 10. 12.]
 [ 5. 16. 18.]]
